[package]
name = "wgpu-native"
version = "0.2.6"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
edition = "2018"
description = "WebGPU native implementation on gfx-hal"
homepage = "https://github.com/gfx-rs/wgpu"
repository = "https://github.com/gfx-rs/wgpu"
keywords = ["graphics"]
license = "MPL-2.0"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = []
local = []
remote = ["serde"]
metal-auto-capture = ["gfx-backend-metal/auto-capture"]
window-winit = ["winit", "gfx-backend-empty/winit"]

[dependencies]
arrayvec = "0.4"
bitflags = "1.0"
copyless = "0.1"
lazy_static = "1.1.0"
log = "0.4"
hal = { package = "gfx-hal", version = "0.2" }
gfx-backend-empty = { version = "0.2" }
gfx-backend-vulkan = { version = "0.2", optional = true }
gfx-backend-dx11 = { version = "0.2", optional = true }
gfx-backend-dx12 = { version = "0.2", optional = true }
gfx-backend-metal = { version = "0.2", optional = true }
gfx-backend-gl = { version = "0.2", optional = true }
parking_lot = { version = "0.8" }
rendy-memory = "0.3"
rendy-descriptor = "0.3"
serde = { version = "1.0", features = ["serde_derive"], optional = true }
vec_map = "0.8"
winit = { version = "0.19", optional = true }
