[package]
name = "wgpu-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "WebGPU types"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]

[features]
trace = ["serde"]
replay = ["serde"]

[dependencies]
bitflags.workspace = true
serde = { workspace = true, features = ["serde_derive"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys.workspace = true
web-sys = { workspace = true, features = [
    "ImageBitmap",
    "HtmlVideoElement",
    "HtmlCanvasElement",
    "OffscreenCanvas",
] }

[dev-dependencies]
serde_json.workspace = true
