[package]
name = "wgpu-types"
version = "0.16.0"
authors = ["wgpu developers"]
edition = "2021"
description = "WebGPU types"
homepage = "https://wgpu.rs/"
repository = "https://github.com/gfx-rs/wgpu"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]

[lib]

[features]
trace = ["serde"]
replay = ["serde"]
strict_asserts = []

[dependencies]
bitflags = "2"
serde = { version = "1", features = ["serde_derive"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.60"
web-sys = { version = "0.3.60", features = [
    "ImageBitmap",
    "HtmlVideoElement",
    "HtmlCanvasElement",
    "OffscreenCanvas",
] }

[dev-dependencies]
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1.0.96"
