[package]
name = "examples"
version = "0.1.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
publish = false

[[bin]]
name = "hello_triangle"
path = "hello_triangle_rust/main.rs"

[[bin]]
name = "hello_compute"
path = "hello_compute_rust/main.rs"

[features]
default = []
remote = ["wgpu-native/remote"]
metal = ["wgpu/metal"]
dx11 = ["wgpu/dx11"]
dx12 = ["wgpu/dx12"]
vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu-native = { path = "../wgpu-native" }
wgpu = { path = "../wgpu-rs", features=["winit"] }
env_logger = "0.5"
