[package]
name = "wgpu-repeated-compute-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu repeated compute example"
publish = false

[[bin]]
name = "repeated-compute"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
futures-intrusive.workspace = true
getrandom = { version = "0.2.10", features = ["js"] }
log.workspace = true
pollster.workspace = true
wgpu.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
wasm-bindgen-futures.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
wgpu-test.workspace = true
