name: validation-windows
on:
  pull_request:
    paths:
      - '.github/workflows/validation-windows.yml'
      - 'tests/out/hlsl/*.hlsl'
      - 'xtask/**'

jobs:
  validate-windows-dxc:
    name: HLSL via DXC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add DirectXShaderCompiler
        uses: napokue/setup-dxc@v1.1.0

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            xtask -> target

      - run: cargo xtask validate hlsl dxc

  validate-windows-fxc:
    name: HLSL via FXC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add fxc bin to PATH
        run: |
          Get-Childitem -Path "C:\Program Files (x86)\Windows Kits\10\bin\**\x64\fxc.exe" `
          | Sort-Object -Property LastWriteTime -Descending `
          | Select-Object -First 1 `
          | Split-Path -Parent `
          | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            xtask -> target

      - run: cargo xtask validate hlsl fxc
